POST http://localhost:8000/api/v1/device
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJoZWFsdGgtaW90LWJhY2tlbmQiLCJzdWIiOiI2MzUzNjJkZWE1YWMyY2Q2NThiMzk2NmYiLCJleHAiOjE2NjY0OTU1ODYsImlhdCI6MTY2NjQwOTE4Nn0.NrZr5S9TpyONJiCbeYiBBH3s7Pr9pJ61upvwFaglb6I
Content-Type: application/json

{
  "name": "test-device1",
  "serial": "123457"
}

###

GET http://localhost:8000/api/v1/device/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJoZWFsdGgtaW90LWJhY2tlbmQiLCJzdWIiOiI2MzUzNjJkZWE1YWMyY2Q2NThiMzk2NmYiLCJleHAiOjE2NjY0OTU1ODYsImlhdCI6MTY2NjQwOTE4Nn0.NrZr5S9TpyONJiCbeYiBBH3s7Pr9pJ61upvwFaglb6I

###

GET http://localhost:8000/api/v1/device/63536310a5ac2cd658b39670
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJoZWFsdGgtaW90LWJhY2tlbmQiLCJzdWIiOiI2MzUzNjJkZWE1YWMyY2Q2NThiMzk2NmYiLCJleHAiOjE2NjY0OTU1ODYsImlhdCI6MTY2NjQwOTE4Nn0.NrZr5S9TpyONJiCbeYiBBH3s7Pr9pJ61upvwFaglb6I

###

PUT http://localhost:8000/api/v1/device/63536310a5ac2cd658b39670/warning?value=0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJoZWFsdGgtaW90LWJhY2tlbmQiLCJzdWIiOiI2MzUzNjJkZWE1YWMyY2Q2NThiMzk2NmYiLCJleHAiOjE2NjY0OTU1ODYsImlhdCI6MTY2NjQwOTE4Nn0.NrZr5S9TpyONJiCbeYiBBH3s7Pr9pJ61upvwFaglb6I

###

POST http://localhost:8000/api/v1/device/data
Content-Type: application/json

{
  "serial": "123456",
  "status": {
    "battery": 10,
    "locating": true,
    "wearing": true
  },
  "sensor": {
    "heart_rate": 170,
    "longitude": 116.470098,
    "latitude": 39.992838
  }
}

###

GET http://localhost:8000/api/v1/device/data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJoZWFsdGgtaW90LWJhY2tlbmQiLCJzdWIiOiI2MzUzNjJkZWE1YWMyY2Q2NThiMzk2NmYiLCJleHAiOjE2NjY0OTU1ODYsImlhdCI6MTY2NjQwOTE4Nn0.NrZr5S9TpyONJiCbeYiBBH3s7Pr9pJ61upvwFaglb6I

###